force-app/main/default/objects/SystemAdminId__c/SystemAdminId__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SystemAdminId</label>
</CustomObject>

force-app/main/default/objects/SystemAdminId__c/fields/AdminId__c.field-meta.xml
<CustomField>
    <fullName>AdminId__c</fullName>
    <label>AdminId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Help_Class_New.cls
public class Help_Class_New {
    public static void UserIsInactive(User UserRecord){
        if(UserRecord.IsActive==false){
           futuremethod(UserRecord.Id);
        }
    }
    @future
    public static void futuremethod(Id UserRecord){
         List<Account> accList=[Select Id,Name,OwnerId from account where OwnerId=:UserRecord];
        Id UserAdminId=(Id)SystemAdminId__c.getOrgDefaults().AdminId__c;
           user AdminNameUserId=[Select Id,Name from User where ProfileId=:UserAdminId][0];
        System.debug(AdminNameUserId);
             //  System.debug(UserAdminId);
            //System.debug(AdminNameUserId);
            for(Account acc:accList){
                acc.ownerId=AdminNameUserId.Id;
            }
            update accList;
    }
}