force-app/main/default/objects/AccountCustom__c/AccountCustom__c.object-meta.xml
<CustomObject>
    <label>AccountCustom</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountCustoms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountCustom__c.field-meta.xml
<CustomField>
    <fullName>AccountCustom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountCustom</label>
    <referenceTo>AccountCustom__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProductCustom__c.field-meta.xml
<CustomField>
    <fullName>ProductCustom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductCustom</label>
    <referenceTo>ProductCustom__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Connect</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductCategory__c/ProductCategory__c.object-meta.xml
<CustomObject>
    <label>ProductCategory</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductCategorys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCategory__c/fields/ProductCustom__c.field-meta.xml
<CustomField>
    <fullName>ProductCustom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductCustom</label>
    <referenceTo>ProductCustom__c</referenceTo>
    <relationshipLabel>ProductCategorys</relationshipLabel>
    <relationshipName>ProductCategorys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductCustom__c/ProductCustom__c.object-meta.xml
<CustomObject>
    <label>ProductCustom</label>
    <nameField>
        <label>Producct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductCustoms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SchemaCustom__c/SchemaCustom__c.object-meta.xml
<CustomObject>
    <label>SchemaCustom</label>
    <nameField>
        <label>SchemaCustom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SchemaCustoms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SchemaCustom__c/fields/AccountCustom__c.field-meta.xml
<CustomField>
    <fullName>AccountCustom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountCustom</label>
    <referenceTo>AccountCustom__c</referenceTo>
    <relationshipLabel>SchemaCustoms</relationshipLabel>
    <relationshipName>SchemaCustoms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SchemaCustom__c/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductCategory</label>
    <referenceTo>ProductCategory__c</referenceTo>
    <relationshipLabel>SchemaCustoms</relationshipLabel>
    <relationshipName>SchemaCustoms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SchemaCustom__c/fields/ProductCustom__c.field-meta.xml
<CustomField>
    <fullName>ProductCustom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductCustom</label>
    <referenceTo>ProductCustom__c</referenceTo>
    <relationshipLabel>SchemaCustoms</relationshipLabel>
    <relationshipName>SchemaCustoms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SchemaCustom__c/fields/State_Date__c.field-meta.xml
<CustomField>
    <fullName>State_Date__c</fullName>
    <label>State Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SchemaCustom__c/fields/Svalue__c.field-meta.xml
<CustomField>
    <fullName>Svalue__c</fullName>
    <label>Svalue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InvoiceTriggerHandler.cls
public class InvoiceTriggerHandler {
	//After Insert Invoice Method Call
    public static void insertInvoice(List<Invoice__c> invoiceRecord){
        Set<Id> accountCustomId=new Set<Id>();
        Set<Id> productCustomId=new Set<Id>();
        Set<Date> Dateof=new Set<Date>();
        Map<String,String> mapOf=new Map<String,String>();
        for(Invoice__c var:invoiceRecord){
            accountCustomId.add(var.AccountCustom__c);
            productCustomId.add(var.ProductCustom__c);
            Dateof.add(var.Date__c);
            mapOf.put(string.valueof(var.AccountCustom__c)+string.valueof(var.ProductCustom__c),var.Value__c+','+var.Status__c);
        }
           List<SchemaCustom__c> Query=[Select Id,Svalue__c,SchemaCustom__c.AccountCustom__c,SchemaCustom__c.ProductCustom__c,SchemaCustom__c.ProductCategory__r.ProductCustom__c from SchemaCustom__c where SchemaCustom__c.AccountCustom__c in:accountCustomId and State_Date__c<=:Dateof and End_Date__c>=:Dateof and (SchemaCustom__c.ProductCustom__c in:productCustomId or  SchemaCustom__c.ProductCategory__r.ProductCustom__c in:productCustomId)];
        System.debug(Query);   
        for(SchemaCustom__c updaterecord:Query){
               if(mapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCustom__c))!=null){
                   if(mapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCustom__c)).split(',')[1]!='Connect'){
                       continue;
                   }
                   else{
                   updaterecord.Svalue__c+=Decimal.valueof(mapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCustom__c)).split(',')[0]);
                   }
               }
               else{
                    if(mapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCategory__r.ProductCustom__c)).split(',')[1]!='Connect'){
                       continue;
                    }else{
                     updaterecord.Svalue__c+=Decimal.valueof(mapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCategory__r.ProductCustom__c)).split(',')[0]);
                    }
                 }
        	}
        	Database.update(Query);
    }
    //After Insert Invoice Method Call
    public static void updateInvoiceRecord(List<Invoice__c> invoiceNewRecord,List<Invoice__c> invoiceOldRecord){
        List<SchemaCustom__c> updateRecords=new List<SchemaCustom__c>();
        Set<Id> accountCustomId=new Set<Id>();
        Set<Id> productCustomId=new Set<Id>();
        Set<Date> Dateof=new Set<Date>();
        Map<String,String> mapOf=new Map<String,String>();
        Map<String,String> oldMapof=new Map<String,String>();
        for(Invoice__c var:invoiceNewRecord){
            accountCustomId.add(var.AccountCustom__c);
            productCustomId.add(var.ProductCustom__c);
            Dateof.add(var.Date__c);
            mapOf.put(string.valueof(var.AccountCustom__c)+string.valueof(var.ProductCustom__c),var.Value__c+','+var.Status__c+','+string.valueof(var.AccountCustom__c)+','+string.valueof(var.ProductCustom__c));
         }
           List<SchemaCustom__c> Query=[Select Id,Svalue__c,SchemaCustom__c.AccountCustom__c,SchemaCustom__c.ProductCustom__c,SchemaCustom__c.ProductCategory__r.ProductCustom__c from SchemaCustom__c where SchemaCustom__c.AccountCustom__c in:accountCustomId and State_Date__c<=:Dateof and End_Date__c>=:Dateof and (SchemaCustom__c.ProductCustom__c in:productCustomId or  SchemaCustom__c.ProductCategory__r.ProductCustom__c in:productCustomId)];
           for(SchemaCustom__c updaterecord:Query){
               if(mapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCustom__c))!=null){
                   if(mapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCustom__c)).split(',')[1]!='Connect'){
                       continue;
                   }
                   else{
                       updaterecord.Svalue__c=Decimal.valueof(mapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCustom__c)).split(',')[0]);  
                    }
               }
               else{
                    if(mapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCategory__r.ProductCustom__c)).split(',')[1]!='Connect'){
                       continue;
                    }else{
                     updaterecord.Svalue__c=Decimal.valueof(mapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCategory__r.ProductCustom__c)).split(',')[0]);
                    }
                 }
        	}
          updateRecords.addAll(Query);
        accountCustomId.clear();
        productCustomId.clear();
        Dateof.clear();
        //mapOf.clear();
        for(Invoice__c var:invoiceOldRecord){
            accountCustomId.add(var.AccountCustom__c);
            productCustomId.add(var.ProductCustom__c);
            Dateof.add(var.Date__c);
         oldMapOf.put(string.valueof(var.AccountCustom__c)+string.valueof(var.ProductCustom__c),var.Value__c+','+var.Status__c+','+string.valueof(var.AccountCustom__c)+','+string.valueof(var.ProductCustom__c)); 
        }
        	List<SchemaCustom__c> oldMapRecord=new List<SchemaCustom__c>();
           List<SchemaCustom__c> Query1=[Select Id,Svalue__c,SchemaCustom__c.AccountCustom__c,SchemaCustom__c.ProductCustom__c,SchemaCustom__c.ProductCategory__r.ProductCustom__c from SchemaCustom__c where SchemaCustom__c.AccountCustom__c in:accountCustomId and State_Date__c<=:Dateof and End_Date__c>=:Dateof and (SchemaCustom__c.ProductCustom__c in:productCustomId or  SchemaCustom__c.ProductCategory__r.ProductCustom__c in:productCustomId)];
           for(SchemaCustom__c updaterecord:Query1){
               if(oldMapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCustom__c))!=NULL){
                    if(oldMapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCustom__c))!=null){
                   if(oldMapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCustom__c)).split(',')[1]!='Connect'){
                       continue;
                   }
                   else{
                   updaterecord.Svalue__c=0;
                    oldMapRecord.add(updaterecord);
                   }
               }
               else{
                    if(oldMapOf.get(string.valueOf(updaterecord.AccountCustom__c)+string.valueOf(updaterecord.ProductCategory__r.ProductCustom__c)).split(',')[1]!='Connect'){
                       continue;
                    }else{
                     updaterecord.Svalue__c=0;
                     oldMapRecord.add(updaterecord);
                    }
                 }
               }
        	}
        if(oldMapRecord.size()!=0)
        updateRecords.addAll(oldMapRecord);
        Database.update(updateRecords);
    }
}