force-app/main/default/objects/Opp_Duplicator__c/Opp_Duplicator__c.object-meta.xml
<CustomObject>
    <label>Opp_Duplicator</label>
    <nameField>
        <label>Opp_Duplicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opp_Duplicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Duplicator__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opp_Duplicators</relationshipLabel>
    <relationshipName>Opp_Duplicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Duplicator__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <label>Opportunity Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Question4_Apex_Class.cls
/***************************************************************************************************
 * Created By 	: Sameer Nandan
 * Created Date : 05-11-108
 * Class Name 	: Question4_Apex_Class
 * Description 	: Create Opportunities Duplicate record type
 * *************************************************************************************************/
public class Question4_Apex_Class {
    public void createDuplicateRecord(){
        List<Opp_Duplicator__c> oppList1=new List<Opp_Duplicator__c>();
        List<Opportunity> oppList= [select id,name,RecordTypeId from Opportunity];
        for(Opportunity opp:oppList){
            Opp_Duplicator__c ob=new Opp_Duplicator__c();
             ob.Opportunity__c=opp.Name;
             ob.Opportunity_Id__c=opp.Id;
             ob.RecordType.name=opp.RecordType.name;
            System.debug(opp.RecordTypeId);
            oppList1.add(ob);
        }
        insert oppList1;
    }
}