force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Citys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Citys</relationshipLabel>
    <relationshipName>Citys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Other_Info__c/Other_Info__c.object-meta.xml
<CustomObject>
    <label>Other Info</label>
    <nameField>
        <label>Other Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Other Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Other_Info__c/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <label>Zipcode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Question2_Apex_Class.cls
/***************************************************************************************************
 * Created By 	: Sameer Nandan
 * Created Date : 05-11-108
 * Class Name 	: Question2_Apex_Class
 * Description 	: Update all lead with address match "other info" object field
 * *************************************************************************************************/
public class Question2_Apex_Class {
    public void updateAllLead(){
        List<Other_Info__c> otherinfolist=[select id,city__c,state__c,zipcode__c from Other_Info__c];
        List<Lead> leadList=[select id,PostalCode,State,City from lead];
        for(Lead ld:leadList){
            for(Other_Info__c info:otherinfolist){
                if(ld.State==info.state__c && ld.City==info.city__c){
                 ld.PostalCode= string.valueOf(info.zipcode__c);
                }
            }
        }
        update leadList;
    }
}