force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CustomVariable</label>
</CustomObject>

force-app/main/default/objects/Account_Custom_Object__c/Account_Custom_Object__c.object-meta.xml
<CustomObject>
    <label>Account Custom Object</label>
    <nameField>
        <label>Account Custom Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Custom Object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Custom_Object__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Custom Object</relationshipLabel>
    <relationshipName>Account_Custom_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountCodeMatching.cls
@RestResource(urlmapping='/matchAccountCode/*')
global class AccountCodeMatching {
    @HttpPost
    global static Temp insertAccount(String Name,Integer AccountCode){
        Temp result=new Temp();
    Account_Custom_Object__c ob=new Account_Custom_Object__c();
        ob.Name=result.NameOfCustomObject=Name;
        ob.Account_Code__c=result.AccountCode=AccountCode;
        Account acc=[Select Id,Name from Account where Account_Code__c=:AccountCode][0];
        if(acc!=null){
        	ob.Account__c=acc.id;
            result.AccountName=acc.Name;
            result.AccountId=acc.Id;
            insert ob;
        }
        return  result;
    }
    global class Temp{
        String NameOfCustomObject;
        string AccountName;
        integer AccountCode;
        Id AccountId;
    }
}