force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Marchandise__c.field-meta.xml
<CustomField>
    <fullName>Marchandise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marchandise</label>
    <referenceTo>Marchandise__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marchandise__c/Marchandise__c.object-meta.xml
<CustomObject>
    <label>Marchandise</label>
    <nameField>
        <label>Maechend Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marchandises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marchandise__c/fields/S_N__c.field-meta.xml
<CustomField>
    <fullName>S_N__c</fullName>
    <label>S.N.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LineItemTriggerHandler.cls
public class LineItemTriggerHandler {
     //Method Call After Insert A record in "Line_Item__c" Object.
	 public static void insertAfter(List<Line_Item__c> records){
        integer count=Integer.valueOf([Select Count(Id) countRecords from Line_Item__c][0].get('countRecords'));
        List<Marchandise__c> listofMarchd=[Select Id,S_N__c From Marchandise__c order by CreatedDate DESC Limit 3];
         Map<Decimal,Id> mapmarch=New Map<Decimal,Id>();
         for(Marchandise__c var:listofMarchd){
             mapmarch.put(var.S_N__c,var.Id);
         }
         System.debug(mapmarch);
        Set<Id> lineitemId=new Set<Id>();
        for(Line_Item__c var:records){
            lineitemId.add(var.id);
        }
        Map<Id,Integer> mapOfLineItem=new Map<Id,Integer>();
        for(Line_Item__c data:records){
            if(!mapOfLineItem.containsKey(data.Id)){
               if(Math.mod(count,3)==0){
                    mapOfLineItem.put(data.Id,3);
                }
                else{
                    mapOfLineItem.put(data.Id,Math.mod(count,3));
                }
                count++;
            }
        }
        List<Line_Item__c> updateRecords=new List<Line_Item__c>();
         Id marchdId;
         for(Id recordId:lineitemId){
             marchdId=mapmarch.get(mapOfLineItem.get(recordId));
             updateRecords.add(new Line_Item__c(Id=recordId,S_N__c=mapOfLineItem.get(recordId),Marchandise__c=marchdId));
         }
        Database.update(updateRecords);
    }
}